#######################################################
### example for Github Container Registry (ghcr.io)
###
### Your container image name will be:
###   ghcr.io/<github-account>/<repo-name>:latest
###
#######################################################
#######################################################

name: "Docker build & push"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [closed]
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set vars
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}:latest" >>${GITHUB_ENV}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push Docker image"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}
          build-args: |
            BOT_NAME=${{ github.repository_owner }}-${{ github.event.repository.name }}
